#Email 인증
mail:
  host: smtp.gmail.com
  port: 587
  username: "ssary.official@gmail.com"
  password: "lnxsqxqjjqnanlhr"
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
          required: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000
  auth-code-expiration-millis: 1800000  # expiration-millis : 30 min

